# These are supported funding model platforms

github: [pathum-lakshan]
patreon: PathumLakshan
open_collective: pathum-lakshan
ko_fi: pathumlakshan
liberapay: pathum-lakshan
issuehunt: pathum-lakshan
custom: https://www.linkedin.com/in/pathum-lakshan-b38395244/

