# These are supported funding model platforms

github: [pathum-lakshan]
patreon: pathum-lakshan
open_collective: pathum-lakshan
ko_fi: pathum-lakshan
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: Spring-Boot-With-Spring-Security Project
liberapay: pathum-lakshan
issuehunt: pathum-lakshan
otechie: pathum-lakshan
lfx_crowdfunding: Spring-Boot-With-Spring-Security Project
custom: https://www.linkedin.com/in/pathum-lakshan-b38395244/

